const projects=[
{id:'sandro',name:'Sandro Fernández Transportes',client:'Sandro Fernández Transportes',category:'web',type:'Proyecto para cliente',url:'https://sandrofernandeztransportes.com.uy/',label:'Web corporativa',desc:'Sitio corporativo para una empresa uruguaya especializada en transporte forestal. Presenta servicios, flota, cobertura, certificaciones y contacto con una interfaz clara y sólida.',tags:['Web corporativa','Industria','Responsive'],mock:'sandro',headline:'Transporte que mueve industria.',kicker:'SEGURIDAD · EXPERIENCIA · CONFIANZA'},
{id:'jarama',name:'Jarama Home & Deco',client:'Jarama',category:'ecommerce web',type:'Proyecto para cliente · En desarrollo',url:'https://rodrigobrun.github.io/PruebaJarama/',label:'E-commerce',desc:'Experiencia de comercio electrónico para una marca de muebles, decoración y accesorios, con catálogo, filtros, carrito y estructura administrativa.',tags:['E-commerce','UX/UI','Catálogo'],mock:'jarama',headline:'Tu casa, tu espacio.',kicker:'NUEVA COLECCIÓN'},
{id:'celeste',name:'Celeste en Agenda',client:'Proyecto propio',category:'product web',type:'Proyecto interno',url:'https://rodribru.github.io/Partidos-de-Uruguay-Mundial/',label:'Experiencia digital',desc:'Micrositio para acompañar a Uruguay durante el Mundial 2026 y guardar los partidos en calendarios digitales.',tags:['Micrositio','Calendario','Interacción'],mock:'celeste',headline:'URUGUAY 2026',kicker:'LA CELESTE EN EL MUNDIAL'},
{id:'syb',name:'Salud y Bienestar UY',client:'Proyecto propio',category:'product web',type:'Proyecto interno',url:'https://rodrigobrun.github.io/SYB/',label:'Plataforma digital',desc:'Plataforma de nutrición, entrenamiento y bienestar con calculadoras, rutinas, recursos y herramientas interactivas.',tags:['Producto digital','UX/UI','Herramientas'],mock:'syb',headline:'Tu salud. Tu ritmo.',kicker:'BIENESTAR EN UN SOLO LUGAR'}
];
const services=[
{n:'01',name:'Branding e identidad',summary:'Una marca reconocible, coherente y lista para crecer.',body:'Definimos la dirección estratégica y construimos un sistema visual que pueda vivir en todos los puntos de contacto.',items:['Estrategia de marca','Identidad visual','Sistema gráfico','Manual de marca','Aplicaciones','Dirección de arte']},
{n:'02',name:'Diseño y desarrollo web',summary:'Sitios que comunican rápido, funcionan bien y se sienten propios.',body:'Diseñamos y desarrollamos experiencias responsive con foco en claridad, conversión y rendimiento.',items:['Arquitectura','UX/UI','Frontend','Responsive','SEO inicial','Integraciones']},
{n:'03',name:'E-commerce y reservas',summary:'Experiencias digitales preparadas para vender, reservar y escalar.',body:'Creamos catálogos, flujos de compra, sistemas de turnos y paneles administrativos adaptados al negocio.',items:['Catálogo','Carrito','Pagos','Reservas','Panel admin','Automatizaciones']},
{n:'04',name:'Estrategia y marketing digital',summary:'Una dirección clara para comunicar con intención.',body:'Ordenamos mensajes, canales y contenido para que la marca construya presencia y oportunidades reales.',items:['Estrategia digital','Contenido','Campañas','Mensajes clave','Roadmap','Medición']},
{n:'05',name:'Productos digitales',summary:'Herramientas, plataformas y experiencias que resuelven algo concreto.',body:'Transformamos ideas en productos interactivos, automatizaciones y soluciones a medida.',items:['Web apps','MVP','Dashboards','Automatización','APIs','Sistemas internos']}
];
const qs=(s,c=document)=>c.querySelector(s),qsa=(s,c=document)=>[...c.querySelectorAll(s)];
function projectVisual(p){return `<div class="project-visual"><div class="project-browser"><div class="mini-bar"><i></i><i></i><i></i></div><div class="mock-page mock-page--${p.mock}"><small>${p.kicker}</small><strong>${p.headline}</strong>${p.mock==='celeste'?'<span>URU &nbsp; VS &nbsp; ESP</span>':''}</div></div></div>`}
function renderProjects(){const grid=qs('#project-grid');if(!grid)return;grid.innerHTML=projects.map(p=>`<article class="project-card reveal" data-category="${p.category}">${projectVisual(p)}<div class="project-info"><div><p>${p.label}</p><h3>${p.name}</h3><p>${p.type}</p></div><button class="project-open" type="button" data-project="${p.id}"><span>Ver caso</span><i class="ph ph-arrow-up-right" aria-hidden="true"></i></button></div></article>`).join('');observeReveals()}
function renderServices(){const deck=qs('#service-deck');if(deck)deck.innerHTML=services.map(s=>`<article class="service-card"><span>${s.n}</span><div><h3>${s.name}</h3><p>${s.summary}</p></div><button type="button" aria-expanded="false" aria-label="Abrir ${s.name}"><i class="ph-bold ph-plus" aria-hidden="true"></i></button><div class="service-details"><p>${s.body}</p><ul>${s.items.map(i=>`<li>${i}</li>`).join('')}</ul></div></article>`).join('');const full=qs('#services-full');if(full)full.innerHTML=services.map(s=>`<article class="capability-row"><span>${s.n}</span><div><h2>${s.name}</h2><p>${s.body}</p></div><ul>${s.items.map(i=>`<li>${i}</li>`).join('')}</ul></article>`).join('')}
function initFilters(){qsa('.project-filters button').forEach(b=>b.addEventListener('click',()=>{qsa('.project-filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');qsa('.project-card').forEach(c=>c.hidden=!(b.dataset.filter==='all'||c.dataset.category.includes(b.dataset.filter))) }))}
function initServices(){qsa('.service-card').forEach(card=>{const b=qs('button',card);b.addEventListener('click',()=>{const open=card.classList.toggle('open');b.setAttribute('aria-expanded',String(open))})})}
function initModal(){const modal=qs('#project-modal');if(!modal)return;let lastFocus;document.addEventListener('click',e=>{const btn=e.target.closest('[data-project]');if(!btn)return;const p=projects.find(x=>x.id===btn.dataset.project);if(!p)return;lastFocus=btn;qs('#modal-content').innerHTML=`<p class="section-index">${p.label} / ${p.type}</p><h2 id="modal-title">${p.name}</h2><p>${p.desc}</p><div class="modal-project-visual"><iframe title="${p.name}" src="${p.url}" loading="lazy"></iframe></div><div class="modal-tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><p><a class="pill-button pill-button--dark" href="${p.url}" target="_blank" rel="noopener noreferrer"><span>Visitar sitio real</span><b aria-hidden="true"><i class="ph-bold ph-arrow-up-right"></i></b></a></p>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('locked');qs('.modal-close').focus()});function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('locked');qs('#modal-content').innerHTML='';lastFocus?.focus()}qsa('[data-close-modal]',modal).forEach(x=>x.addEventListener('click',close));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))close()})}
function initPreview(){const picker=qs('#project-picker'),frame=qs('#live-frame'),iframe=qs('#live-iframe');if(!picker||!frame||!iframe)return;picker.innerHTML=projects.map((p,i)=>`<button type="button" data-id="${p.id}" class="${i===0?'active':''}"><i class="ph ph-browser" aria-hidden="true"></i><span>${p.name}</span></button>`).join('');function load(id){const p=projects.find(x=>x.id===id);qsa('button',picker).forEach(x=>x.classList.toggle('active',x.dataset.id===id));qs('#live-url').textContent=p.url.replace(/^https?:\/\//,'');qs('#live-open').href=p.url;qs('#fallback-link').href=p.url;iframe.classList.remove('loaded');qs('#loading-state').style.display='grid';qs('#preview-fallback').style.display='none';iframe.src=p.url;setTimeout(()=>{qs('#loading-state').style.display='none';iframe.classList.add('loaded')},1800)}picker.addEventListener('click',e=>{if(e.target.matches('button'))load(e.target.dataset.id)});qsa('.device-switcher button').forEach(b=>b.addEventListener('click',()=>{qsa('.device-switcher button').forEach(x=>x.classList.remove('active'));b.classList.add('active');frame.className=`live-frame ${b.dataset.device} reveal in-view`}));load(projects[0].id)}
function initIdeaLab(){const form=qs('#idea-builder'),result=qs('#idea-result');if(!form)return;const copy={vender:['Una experiencia que convierte interés en acción.','Identidad enfocada + recorrido comercial + web preparada para convertir.'],posicionar:['Una marca que se vea tan profesional como el trabajo que hace.','Sistema visual + mensajes claros + sitio con autoridad.'],reservas:['Menos mensajes perdidos. Más turnos confirmados.','Experiencia de reserva + automatización + panel de gestión.'],lanzar:['Una idea nueva necesita una entrada imposible de ignorar.','Concepto de marca + landing de lanzamiento + sistema para crecer.']};form.addEventListener('submit',e=>{e.preventDefault();const g=qs('#goal-select').value,v=qs('#vibe-select').selectedOptions[0].textContent;result.innerHTML=`<span>ATRY / CONCEPT ${String(Math.floor(Math.random()*900)+100)}</span><h3>${copy[g][0]}</h3><p>${copy[g][1]} Dirección: ${v}.</p><div><b>IDENTITY</b><b>EXPERIENCE</b><b>GROWTH</b></div>`})}
function initPlayground(){const canvas=qs('#brand-canvas');if(!canvas)return;const ranges=['energy-range','clarity-range','motion-range'].map(id=>qs('#'+id));function paint(){const [e,c,m]=ranges.map(r=>+r.value);canvas.style.background=`linear-gradient(${120+m}deg,hsl(${190+e/4} 85% ${8+c/12}%),hsl(${205+m/5} 85% ${38+e/8}%),hsl(${240+c/5} 70% 55%))`;canvas.style.transform=`perspective(1000px) rotateX(${(m-50)/20}deg) rotateY(${(e-50)/25}deg)`;qs('#canvas-caption').textContent=`${e>66?'Audaz':'Equilibrada'} · ${c>66?'Clara':'Exploratoria'} · ${m>66?'Dinámica':'Precisa'}`}ranges.forEach(r=>r.addEventListener('input',paint));qs('#randomize-brand').addEventListener('click',()=>{ranges.forEach(r=>r.value=Math.floor(Math.random()*100));paint()});paint()}
function observeReveals(){const els=qsa('.reveal:not(.watched)');const io=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add('in-view');io.unobserve(x.target)}}),{threshold:.14});els.forEach(el=>{el.classList.add('watched');io.observe(el)})}
function initHeader(){const header=qs('[data-header]');if(header)addEventListener('scroll',()=>header.classList.toggle('is-scrolled',scrollY>30));const toggle=qs('.menu-toggle'),menu=qs('.mobile-menu');if(toggle&&menu){toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');menu.setAttribute('aria-hidden',!open);document.body.classList.toggle('locked',open)});qsa('a',menu).forEach(a=>a.addEventListener('click',()=>toggle.click()))}}
function initCursor(){if(!matchMedia('(pointer:fine)').matches)return;const d=qs('.cursor-dot'),r=qs('.cursor-ring');addEventListener('mousemove',e=>{d.style.left=r.style.left=e.clientX+'px';d.style.top=r.style.top=e.clientY+'px'});qsa('a,button').forEach(el=>el.addEventListener('mouseenter',()=>{r.style.width='58px';r.style.height='58px'}));qsa('a,button').forEach(el=>el.addEventListener('mouseleave',()=>{r.style.width='36px';r.style.height='36px'}))}
function initScroll(){addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;qs('.scroll-progress span')&&(qs('.scroll-progress span').style.width=(scrollY/h*100)+'%')})}
function initForm(){const f=qs('#contact-form');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();qs('#form-status').textContent='Formulario listo para conectar. Todavía no se envió ningún dato.'})}
renderProjects();renderServices();initFilters();initServices();initModal();initPreview();initIdeaLab();initPlayground();initHeader();initCursor();initScroll();initForm();observeReveals();qs('#year')&&(qs('#year').textContent=new Date().getFullYear());
